import {
  AmenityItem,
  FloorPlanUnit,
  CommuteDestination,
  SpecificationCategory,
  ConsultantItem,
  TrackRecordProject,
  MasterPlanPoint,
} from "./types";

export const projectSnapshot = {
  name: "Silver Horizon",
  tagline: "A New Benchmark in Elevated Living",
  developer: "GreenEdge Infracon",
  developerFull: "GreenEdge Infracon Pvt. Ltd.",
  developerBio:
    "GreenEdge Infracon is committed to creating thoughtfully designed spaces that blend timeless architecture, quality craftsmanship, and future-ready living. With a focus on innovation, sustainability and meticulous attention to detail, every development is crafted to offer lasting value and an elevated lifestyle for generations to come.",
  address: "No.127/3 & 128/4, KhajiSonnenahalli, Bidarahalli Hobli, Bangalore East - 560067",
  locationName: "East Bengaluru (Between Whitefield and Hoskote, adjoining PRR)",
  phonePrimary: "+91 98806 66189",
  phoneSecondary: "+91 96639 27740",
  phoneRaw: "9880666189",
  email: "info@greenedgeinfracon.com",
  website: "www.greenedgeinfracon.com",
  rera: "PRM/KA/RERA/1251/446/PR/250925/008120",
  storeyCount: "32-Storey Landmark",
  totalFloors: "G + 32 Floors",
  openSpace: "76% Open Space",
  ceilingHeight: "10-Foot Ceiling Height",
  clubhouseArea: "14,962 SQFT (The Pavilion)",
  amenitiesCount: "35+ Modern Amenities",
  parking: "Triple Basement Parking + EV Charging for Every Space",
  unitGap: "6–12 Feet Open Space Between Units",
  lalbaghProximity: "500 Meters to East Lalbagh",
  configuration: "3 & 4 BHK Luxury Residences & Duplex Collection",
  sizes: "3 BHK: 1890 – 2015 SQFT | 4 BHK Duplex: 2975 – 3480 SQFT",
};

export const keyHighlights = [
  { value: "32", label: "Storey Landmark", sub: "Mediterranean Architecture" },
  { value: "14,962", label: "SQFT Clubhouse", sub: "The Pavilion on 1st Floor" },
  { value: "76%", label: "Open Space", sub: "Lush Greens & Trails" },
  { value: "10-Foot", label: "Ceiling Height", sub: "Expansive Volume & Light" },
  { value: "35+", label: "Curated Amenities", sub: "Sports, Wellness & Leisure" },
  { value: "6–12 FT", label: "Open Separation", sub: "Privacy Between Units" },
  { value: "500 M", label: "To East Lalbagh", sub: "Serene Green Proximity" },
  { value: "100%", label: "EV Provision", sub: "In Triple Basement Parking" },
];

export const amenitiesData: AmenityItem[] = [
  {
    id: "clubhouse",
    title: "The Pavilion Clubhouse",
    category: "14,962 SQFT OF LUXURY",
    tagline: "Social House for Private Galas & Corporate Networking",
    description:
      "Designed as an exclusive retreat for leisure, wellness, and connection, the 14,962 sq.ft clubhouse brings together thoughtfully curated amenities in an atmosphere of understated luxury.",
    imageUrl: "/assets/silver_horizon/indoor_pool.webp",
    images: [
      "/assets/silver_horizon/indoor_pool.webp",
      "/assets/silver_horizon/jacuzzi.webp",
      "/assets/silver_horizon/indoor_gym.webp",
      "/assets/silver_horizon/coworking_space.webp",
      "/assets/silver_horizon/banquet_hall.webp",
      "/assets/silver_horizon/clubhouse_layout_plan.webp",
    ],
    bullets: [
      "Indoor Temperature-Controlled Pool with Deck & Kids Pool",
      "Thermal Jacuzzi & Rejuvenation Spa Chambers",
      "High-Tech Strength & Cardio Fitness Gymnasium",
      "Dedicated Co-Working Space & Meeting Pods",
      "Grand Banquet & Multipurpose Party Hall",
      "Indoor Games Room & Professional Table Tennis Arena",
      "Private Guest Rooms & Tuition / Activity Centre",
      "Al Fresco Dining Area & Outdoor Cards Pavilion",
    ],
  },
  {
    id: "active-sports",
    title: "Active Living & Sports",
    category: "HEALTH & MOVEMENT",
    tagline: "Designed for Movement, Energy & Play",
    description:
      "Comprehensive sports facilities and open recreation zones encourage active, energetic lifestyles for residents of all ages.",
    imageUrl: "/assets/silver_horizon/sport_basketball.webp",
    images: [
      "/assets/silver_horizon/sport_basketball.webp",
      "/assets/silver_horizon/sport_cricket.webp",
      "/assets/silver_horizon/sport_futsal.webp",
      "/assets/silver_horizon/sport_cycling.webp",
      "/assets/silver_horizon/sport_climbing.webp",
      "/assets/silver_horizon/sport_toddler.webp",
    ],
    bullets: [
      "Full-sized Multipurpose Basketball & Pickleball Court",
      "Dedicated Futsal Court with AstroTurf",
      "Enclosed Cricket Practice Net with Bowling Pitch",
      "Dedicated Cycling Zone and Perimeter Jogging Track",
      "Adventure Climbing Wall for Children & Youth",
      "Safe Toddlers Play Area & Sand Pit with Trampoline",
    ],
  },
  {
    id: "nature-community",
    title: "Nature & Community",
    category: "SERENITY & CONNECTION",
    tagline: "Where Every Moment Becomes a Cherished Memory",
    description:
      "A neighbourhood designed around everyday moments rather than occasional events. Shared spaces encourage meaningful connection while preserving quiet privacy.",
    imageUrl: "/assets/silver_horizon/pavilion_amphitheatre.webp",
    images: [
      "/assets/silver_horizon/pavilion_amphitheatre.webp",
      "/assets/silver_horizon/pet_park.webp",
      "/assets/silver_horizon/kids_play_area.webp",
      "/assets/silver_horizon/swing_court.webp",
      "/assets/silver_horizon/sport_reflexology.webp",
      "/assets/silver_horizon/wellness_pool.webp",
    ],
    bullets: [
      "The Pavilion Open-Air Amphitheatre with Giant LED Screen",
      "Dedicated Pet Park ('Where Every Paw Finds Its Place')",
      "Custom Swing Court & Shaded Seating Pavilions",
      "Aroma Gardens & Reflexology Acupressure Pathway",
      "Yoga Lawn & Sunset Viewing Promenade",
      "Interactive Entrance Water Feature & Sculpture Zone",
    ],
  },
  {
    id: "smart-eco",
    title: "Smart Living & Sustainability",
    category: "FUTURE-READY INFRASTRUCTURE",
    tagline: "Built for the Future, Crafted with Intention",
    description:
      "Smart technology that works quietly in the background alongside forward-looking eco-sustainable systems that conserve resources for generations to come.",
    imageUrl: "/assets/silver_horizon/ev_charging.webp",
    images: [
      "/assets/silver_horizon/ev_charging.webp",
      "/assets/silver_horizon/smart_lock_tech.webp",
      "/assets/silver_horizon/water_harvesting.webp",
      "/assets/silver_horizon/aerial_tower_view.webp",
    ],
    bullets: [
      "Biometric Access & Smart Yale / Equivalent Digital Locks",
      "Video Door Phone (VDP) & AI Home Automation Provisions",
      "EV Charging Infrastructure for Every Parking Space",
      "Exclusive Water Treatment Plant (WTP) for Softened Water",
      "Sewage Treatment Plant (STP) with 100% Recycled Water for Flushing & Landscaping",
      "Rainwater Harvesting Tanks & Ground Recharge Wells",
      "100% DG Power Backup for Lifts, Pumps & Common Areas",
      "Organic Waste Converters (OWC) for Zero-Waste Living",
    ],
  },
];

export const floorPlansData: FloorPlanUnit[] = [
  {
    id: "unit-01",
    unitNo: "Unit 01",
    title: "3 BHK Residence (Unit 01)",
    type: "3 BHK",
    facing: "West Facing",
    sbua: "1890 SQFT",
    carpetArea: "1150 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_01.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "West Facing main entrance with Vastu compliance",
      "Expansive Living & Dining hall (18'0\" x 12'0\") with sunlit balcony",
      "Spacious Master Bedroom with private bath and wardrobe recess",
      "10-foot ceiling height creating airy, volumetric luxury",
      "Dedicated Utility Area adjacent to modern kitchen",
      "6-12 ft structural separation ensuring complete acoustic privacy",
    ],
  },
  {
    id: "unit-02",
    unitNo: "Unit 02",
    title: "3 BHK Residence (Unit 02)",
    type: "3 BHK",
    facing: "North Facing",
    sbua: "1990 SQFT",
    carpetArea: "1208 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_02.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "North Facing entrance welcoming soft, natural ambient daylight",
      "Large Living & Dining zone (20'0\" x 12'0\") with expansive viewing deck",
      "3 Lavish Bedrooms with large format floor-to-ceiling windows",
      "Smart home biometric lock & video door phone installed",
      "Ergonomic kitchen layout with granite counters and dry balcony",
      "Cross-ventilation designed across living and private quarters",
    ],
  },
  {
    id: "unit-03",
    unitNo: "Unit 03",
    title: "3 BHK Residence (Unit 03)",
    type: "3 BHK",
    facing: "North Facing",
    sbua: "2015 SQFT",
    carpetArea: "1227 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_03.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "Largest 3 BHK single-level configuration with 2015 SQFT SBUA",
      "Grand entertaining living/dining room overlooking East Lalbagh greenery",
      "All 3 Bedrooms featuring en-suite or adjacent designer bathrooms",
      "Premium TOTO / equivalent sanitary fittings and glass shower partitions",
      "High ceiling volume (10 ft) and expansive sliding balcony doors",
      "Dedicated Pooja / Foyer alcove and utility space",
    ],
  },
  {
    id: "unit-04",
    unitNo: "Unit 04",
    title: "3 BHK Residence (Unit 04)",
    type: "3 BHK",
    facing: "North Facing",
    sbua: "1905 SQFT",
    carpetArea: "1153 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_04.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "North Facing entrance with optimized usable carpet area (1153 SQFT)",
      "Open-concept living room flowing into dining and scenic terrace deck",
      "Generous Master Suite with wooden-finish vitrified flooring",
      "Concealed copper wiring with Schneider modular switches",
      "Smart electrical layout with AC provisions in all bedrooms",
      "Quiet corner orientation with three-sided ventilation",
    ],
  },
  {
    id: "unit-05",
    unitNo: "Unit 05",
    title: "3 BHK Residence (Unit 05)",
    type: "3 BHK",
    facing: "East Facing",
    sbua: "1990 SQFT",
    carpetArea: "1212 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_05.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "East Facing entrance designed to capture golden morning sunrise",
      "1212 SQFT Carpet Area with zero dead corridors",
      "Dedicated Home Office / Study alcove provision",
      "Double-coat weather resistant facade and acoustic UPVC glazing",
      "Spacious kitchen with utility yard for laundry equipment",
      "High-speed fiber-optic data and Wi-Fi points throughout",
    ],
  },
  {
    id: "unit-06",
    unitNo: "Unit 06",
    title: "3 BHK Residence (Unit 06)",
    type: "3 BHK",
    facing: "East Facing",
    sbua: "1975 SQFT",
    carpetArea: "1193 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_06.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "East Facing layout overlooking pristine central landscaping",
      "Generously proportioned living spaces and seamless movement flow",
      "3 Luxury Bathrooms with wall-mounted EWCs and concealed cisterns",
      "USB Type-C mobile charging points in master bedroom",
      "Re-Veneer 8-foot entrance door with Yale digital locking",
      "Abundant natural light ensuring cooler indoor microclimate",
    ],
  },
  {
    id: "unit-07",
    unitNo: "Unit 07",
    title: "3 BHK Residence (Unit 07)",
    type: "3 BHK",
    facing: "East Facing",
    sbua: "1985 SQFT",
    carpetArea: "1165 SQFT",
    imageUrl: "/assets/silver_horizon/unit_plan_07.webp",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    highlights: [
      "East Facing orientation with private entryway foyer",
      "Bespoke living-dining space designed for intimate family gatherings",
      "Master bedroom with private sunset balcony and walk-in dresser",
      "Continuous power backup from 100% DG generators",
      "Individual EV charging slot allotted in basement parking",
      "Mediterranean architectural details and textured finishes",
    ],
  },
  {
    id: "duplex-32",
    unitNo: "32nd Floor",
    title: "4 BHK Duplex Sky Collection",
    type: "4 BHK Duplex",
    facing: "Panoramic Skyline",
    sbua: "2975 – 3480 SQFT",
    carpetArea: "1850 – 2190 SQFT",
    imageUrl: "/assets/silver_horizon/duplex_staircase.webp",
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    highlights: [
      "Exclusive Crown Jewel residences situated on the 32nd Floor",
      "Two levels of beautifully connected living designed for evolving families",
      "Dramatic double-height living room with sculptural internal staircase",
      "Expansive sky terraces floating above the clouds with 270° horizon views",
      "Private family lounge on the upper level + 4 palatial bedroom suites",
      "Dedicated maid's quarters with separate entrance and utility",
    ],
  },
];

export const masterPlanLegends: MasterPlanPoint[] = [
  { id: 1, name: "Entry / Exit + Security Portal", category: "Entrance & Arrival" },
  { id: 2, name: "Entrance Water Feature", category: "Entrance & Arrival" },
  { id: 3, name: "Waiting Zone & Drop-off", category: "Entrance & Arrival" },
  { id: 4, name: "Reflexology Pathway (with Aroma Garden)", category: "Nature & Landscape" },
  { id: 5, name: "Yoga Lawn", category: "Sports & Wellness" },
  { id: 6, name: "Seating Bay next to Jogging Track", category: "Nature & Landscape" },
  { id: 7, name: "Cycling Zone", category: "Sports & Wellness" },
  { id: 8, name: "OAT Seating (Amphitheatre)", category: "Family & Kids" },
  { id: 9, name: "OAT Stage & Cinema Screen", category: "Family & Kids" },
  { id: 10, name: "Toddlers Sand Pit Area", category: "Family & Kids" },
  { id: 11, name: "Climbing Wall", category: "Sports & Wellness" },
  { id: 12, name: "Kids Play Area", category: "Family & Kids" },
  { id: 13, name: "Parent's Seating Zone", category: "Family & Kids" },
  { id: 14, name: "Interactive Water Feature", category: "Nature & Landscape" },
  { id: 15, name: "Trampoline Zone", category: "Family & Kids" },
  { id: 16, name: "Basketball Hoop Wall", category: "Sports & Wellness" },
  { id: 17, name: "Music Wall", category: "Family & Kids" },
  { id: 18, name: "Pet Park ('Where Every Paw Finds Its Place')", category: "Family & Kids" },
  { id: 19, name: "Service Road", category: "Infrastructure" },
  { id: 20, name: "Perimeter Driveway", category: "Infrastructure" },
  { id: 21, name: "Multipurpose Court (Basketball + Pickleball)", category: "Sports & Wellness" },
  { id: 22, name: "Sports Viewing Gallery", category: "Sports & Wellness" },
  { id: 23, name: "Futsal Court", category: "Sports & Wellness" },
  { id: 24, name: "Branding Feature Wall", category: "Entrance & Arrival" },
  { id: 25, name: "Cricket Practice Net", category: "Sports & Wellness" },
  { id: 26, name: "Swing Court", category: "Nature & Landscape" },
  { id: 27, name: "Open Gym Zone", category: "Sports & Wellness" },
  { id: 28, name: "Aroma Garden", category: "Nature & Landscape" },
  { id: 29, name: "Entrance Sculpture Zone", category: "Entrance & Arrival" },
  { id: 30, name: "Planting Area & Green Buffers", category: "Nature & Landscape" },
  { id: 31, name: "Entrance Foyer", category: "Entrance & Arrival" },
  { id: 32, name: "Temple", category: "Nature & Landscape" },
  { id: 33, name: "Walking Trail with Seaters", category: "Nature & Landscape" },
];

export const locationsData: CommuteDestination[] = [
  {
    id: "kr-puram",
    name: "K R Puram Hub",
    distance: "15 mins",
    icon: "directions_car",
    category: "Transit",
    times: { driving: 15, transit: 25, walking: 75 },
  },
  {
    id: "itpl",
    name: "ITPL Whitefield",
    distance: "7.0 km (30 mins)",
    icon: "business_center",
    category: "Business",
    times: { driving: 30, transit: 40, walking: 120 },
  },
  {
    id: "orr",
    name: "Outer Ring Road (ORR)",
    distance: "30 mins",
    icon: "alt_route",
    category: "Transit",
    times: { driving: 30, transit: 45, walking: 140 },
  },
  {
    id: "airport",
    name: "Kempegowda Int. Airport",
    distance: "35 mins (via Bypass)",
    icon: "flight_takeoff",
    category: "Transit",
    times: { driving: 35, transit: 55, walking: 300 },
  },
  {
    id: "metro",
    name: "Kadugodi Whitefield Metro",
    distance: "5.2 km",
    icon: "subway",
    category: "Transit",
    times: { driving: 12, transit: 18, walking: 50 },
  },
  {
    id: "bearys",
    name: "Bearys Global Research Triangle",
    distance: "0.5 km (Walking)",
    icon: "apartment",
    category: "Business",
    times: { driving: 2, transit: 5, walking: 6 },
  },
];

export const nearbyPointsOfInterest = {
  businessHubs: [
    { name: "Bearys Global Research Triangle", dist: "0.5 km" },
    { name: "Titanium Tech Park", dist: "6.6 km" },
    { name: "GR Tech Park", dist: "6.9 km" },
    { name: "ITPL (International Tech Park)", dist: "7.0 km" },
    { name: "HM Tech Park", dist: "7.0 km" },
    { name: "SCB Brigade Tech Park", dist: "7.0 km" },
    { name: "ITPB Bengaluru", dist: "7.2 km" },
    { name: "First Technology Park / Place", dist: "7.8 km" },
  ],
  schools: [
    { name: "Jain Heritage School Whitefield", dist: "0.5 km" },
    { name: "Narayana Olympiad School, Goravigere", dist: "1.2 km" },
    { name: "Kids Castle Preschool", dist: "2.5 km" },
    { name: "Vision Montessori Preschool", dist: "2.5 km" },
    { name: "Vagdevi Vilas School", dist: "2.7 km" },
    { name: "Maple Global School", dist: "3.1 km" },
    { name: "Valistus International School", dist: "3.6 km" },
    { name: "Chrysalis High School, Kadugodi", dist: "3.9 km" },
    { name: "DPS Whitefield, Mallasandra", dist: "4.1 km" },
  ],
  hospitals: [
    { name: "Motherhood Clinic, Kannamangala", dist: "1.3 km" },
    { name: "ECHS Polyclinic Whitefield", dist: "1.5 km" },
    { name: "Aaxis Hospitals", dist: "3.8 km" },
    { name: "RxDx Clinics, Kadugodi", dist: "4.2 km" },
    { name: "Arvi Hospital, Hoskote", dist: "5.2 km" },
    { name: "Aster Hospital Whitefield", dist: "6.9 km" },
    { name: "Cloudnine Hospital Whitefield", dist: "7.2 km" },
    { name: "Manipal Hospital Whitefield", dist: "7.4 km" },
  ],
  leisure: [
    { name: "Uptown Square", dist: "1.4 km" },
    { name: "Orion Uptown Mall", dist: "2.8 km" },
    { name: "Park Square Mall", dist: "7.0 km" },
    { name: "Nexus Shantiniketan Mall", dist: "7.2 km" },
    { name: "East Lalbagh Botanical Garden", dist: "0.5 km" },
  ],
  infrastructure: [
    {
      title: "Peripheral Ring Road (PRR)",
      desc: "Adjoining 65-meter (213 ft) Bangalore Business Corridor providing seamless high-speed cross-city mobility.",
      badge: "0 km (Adjoining)",
      img: "/assets/silver_horizon/prr_expressway.webp",
    },
    {
      title: "Metro Connectivity",
      desc: "Whitefield (Kadugodi) Metro station 5.2 km away, connecting to Purple Line and upcoming Airport Metro line.",
      badge: "5.2 km",
      img: "/assets/silver_horizon/metro_train.webp",
    },
    {
      title: "Satellite Town Ring Road (STRR)",
      desc: "Connecting Bengaluru with strategic economic satellite towns for effortless regional transit.",
      badge: "Strategic Corridor",
      img: "/assets/silver_horizon/strr_highway.webp",
    },
    {
      title: "Bengaluru-Chennai Expressway",
      desc: "Transforming Eastern Bengaluru into the nation's premier industrial and lifestyle corridor.",
      badge: "Expressway",
      img: "/assets/silver_horizon/bangalore_chennai_exp.webp",
    },
  ],
};

export const specificationsData: SpecificationCategory[] = [
  {
    title: "Structure & Architecture",
    icon: "architecture",
    items: [
      "RCC Framed Structure with RCC Shear Walls designed for maximum seismic resistance and structural durability.",
      "10-Foot clear ceiling heights across all living, dining, and bedroom spaces.",
      "6 to 12 Feet structural open separation between individual apartment units for superior acoustic insulation and privacy.",
    ],
  },
  {
    title: "Doors, Windows & Automation",
    icon: "door_front",
    items: [
      "Main Entrance Door: Re-Veneer Finish, 8' high with Smart Electric Digital Door Lock System of Yale / equivalent brands.",
      "Internal Doors: Good quality timber frame and shutter with premium ironmongery, 7' for Bedrooms and Toilet doors.",
      "Windows: Premium UPVC / Aluminium sliding windows with bug screen and appropriate heavy-duty hardware.",
      "Home Automation provision in living room and master bedroom + Video Door Phone (VDP) at main entry.",
    ],
  },
  {
    title: "Flooring & Wall Finishes",
    icon: "format_paint",
    items: [
      "Living, Dining, and Bedrooms: High quality large-format vitrified tiles.",
      "Bathrooms: Premium anti-skid ceramic/vitrified tiles with Dado up to false-ceiling level.",
      "Kitchen: Vitrified flooring with Dado up to 3'6\" above counter height.",
      "Internal Walls: Smooth putty finish with primer and two coats of premium acrylic emulsion paint.",
      "External Walls: Textured or smooth finish with two coats of weather-resistant exterior emulsion paint.",
    ],
  },
  {
    title: "Toilets & Plumbing",
    icon: "shower",
    items: [
      "Sanitary & CP fittings of TOTO / equivalent international standard make.",
      "Single lever hot & cold diverter cum shower.",
      "Wall mounted EWC with concealed cistern and dual flush.",
      "Toughened glass partition separating Wet & Dry areas in bathrooms.",
      "Drainage & Sewage: SWR / PVC pipes; Water Supply: CPVC / UPVC pipes and fittings.",
    ],
  },
  {
    title: "Electrical & Data Infrastructure",
    icon: "bolt",
    items: [
      "Concealed copper wiring of Havells / Polycab or equivalent certified make.",
      "Modular switches and sockets of Schneider or equivalent luxury make.",
      "Power sockets for split ACs in all bedrooms and living room.",
      "USB Type-C high-speed charging port in the master bedroom.",
      "Comprehensive kitchen sockets for hob, chimney, refrigerator, microwave, mixer & RO.",
      "100% uninterrupted DG power backup for lifts, water pumps, and all common lighting.",
    ],
  },
  {
    title: "Safety, Security & Car Parking",
    icon: "security",
    items: [
      "24/7 CCTV surveillance cameras at main security gate, basements, and lobbies.",
      "High-speed access-controlled elevators with ARD (Auto Rescue Device) & V3F drives (Schindler or equivalent).",
      "03 eight-passenger passenger lifts + 01 thirteen-passenger service stretcher lift.",
      "Fire sprinkler systems in all flats, corridors, and triple basement floors.",
      "Fire hydrants, extinguishers, and central fire alarm with PA system.",
      "Covered triple basement car parking with power-trowelled smooth concrete flooring.",
      "Dedicated EV charging slot provision for EVERY parking space + visitor car charging & car washing bay.",
    ],
  },
  {
    title: "Eco-Sustainable Facilities",
    icon: "eco",
    items: [
      "Softened water supplied through exclusive in-house Water Treatment Plant (WTP).",
      "Sewage Treatment Plant (STP) with treated water reused for landscape irrigation & flushing.",
      "Rainwater harvesting tanks & groundwater recharge injection wells.",
      "Solar powered lighting for common areas and rooftop zones.",
      "Organic Waste Converters (OWC) for zero-landfill organic waste management.",
    ],
  },
];

export const approvalsData = [
  { name: "BDA Approval", authority: "Bangalore Development Authority", status: "Approved" },
  { name: "Water Permission - PDO", authority: "Kannamangala Gram Panchayath", status: "Sanctioned" },
  { name: "SEIAA Environmental Clearance", authority: "State Level Environment Impact Assessment Authority - Bangalore", status: "Cleared" },
  { name: "KSPCB Consent", authority: "Karnataka State Pollution Control Board", status: "Approved" },
  { name: "FIRE NOC", authority: "Karnataka State Fire & Emergency Services", status: "Sanctioned" },
  { name: "AAI Clearance", authority: "Airport Authority of India", status: "Approved" },
  { name: "BSNL Infrastructure", authority: "Bharat Sanchar Nigam Limited", status: "Approved" },
  { name: "BESCOM Power", authority: "Bangalore Electricity Supply Company Limited", status: "Sanctioned" },
];

export const consultantsData: ConsultantItem[] = [
  {
    role: "Architects",
    name: "DB ARCHITECTS PVT LTD",
    address: "'C' Square, 400/2, Hoodi, Whitefield Main Road, Hoodi (above ICICI Bank), Bengaluru",
  },
  {
    role: "Structural & MEP",
    name: "ALONUM DESIGN",
    address: "Stone Henge Apartments, #411, 4th Floor, Jawahar Nagar, RTC X Roads, Hyderabad - 20",
  },
  {
    role: "Building Services",
    name: "GREETS BUILDING SERVICES PVT. LTD.",
    address: "#177, 9th Main Rd, Sector 7, HSR Layout, Bengaluru - 560102",
  },
  {
    role: "Landscape Architecture",
    name: "ARANYA - THE LANDSCAPE STUDIO",
    address: "102, 2nd Floor, 9th Cross RBI Layout, JP Nagar 7th Phase, Bangalore - 560078",
  },
];

export const trackRecordData: TrackRecordProject[] = [
  {
    title: "GREEN EDGE CASERO",
    type: "2, 2.5 & 3 BHK Residential",
    location: "Seegehalli, Whitefield, Bengaluru",
    imageUrl: "/assets/silver_horizon/track_casero.webp",
  },
  {
    title: "GREEN EDGE SIGNATURE",
    type: "2, 3 & 4 BHK Apartments",
    location: "Varthur Main Road, Whitefield, Bangalore",
    imageUrl: "/assets/silver_horizon/track_signature.webp",
  },
  {
    title: "UNITED SAI GREENWOODS",
    type: "1, 2, 2.5, 3 & 4 BHK",
    location: "Kadugodi, Bengaluru",
    imageUrl: "/assets/silver_horizon/track_greenwoods.webp",
  },
  {
    title: "UNITED DREAMS",
    type: "2 & 3 BHK Apartments",
    location: "Bidarahalli Hobli, Bangalore East Taluk, Karnataka",
    imageUrl: "/assets/silver_horizon/track_dreams.webp",
  },
];
